version: "3.8"

services:
  app:
    container_name: albergue-website
    image: albergue-website
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
